### ISSUE TITLE
Give some explanation on decision

### ISSUE THREAD

**Issue by dels07** [Alikhll/golang-developer-roadmap#22]
I just stumble upon your developer roadmap, as a newbie, I would like to know why you suggesting echo as framework of choice, since most of golang dev I met/talked to prefer no framework so they cannot help explain it.

I'm coming from PHP and Python so community already have general consensus on what framework to use, even PHP community basically advise to start new project using framework mainly due to possible security issue with no framework implementation.

Also some description on other decision would be great.

**Comment by Alikhll** [comment]
First of all, somethings I have added to roadmap basically are coming from my experience with Go, so It is my personal Idea and it might not be 100% correct, of course I am totally open mind to enhance the roadmap based another developer ideas and I have changed some part of that although.
yes, I absolutely agree is it better not to use any third party framework/library because you can do anything with Go, but it is fine for person who has worked with Go over years and has got lots of experience with that, basically for majority of developers I personally suggest to use frameworks, because it helps so much for kind of startupy projects which need to be as much fast as possible, so frameworks help a lot about that and we can not ignore all of them without meaningful reason!
I suggested Echo because it is easy to learn and it is does not need much effort for learning curve, it is very very fast also and it does support  lots of cool features such as Middleware, WebSocket, etc, and it is nice for developing microservices architecture, and also community is behind that and help a lot to grow this framework, lots of people use that in production as I have done personally too, So my idea is it is one of best web framework for Go.
